---
title: "Immune reconstitution - Sep 2021 summary"
author: "Ed Bonneville"
date: "`r Sys.setenv(LANG = 'en_US.UTF-8'); format(Sys.Date(), '%d %B %Y')`"
output: 
  html_document:
    df_print: kable
    toc: yes
    toc_float: 
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Knitr set-up
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(
  echo = FALSE, 
  out.width = "100%", 
  warning = FALSE, 
  message = FALSE
)
options(knitr.kable.NA = '', scipen = 999)

# Prep ggplot2 labellers
atg_labs <- as_labeller(x = c("noATG" = "No ATG", "yesATG" = "ATG"))
cmv_labs <- as_labeller(
  x = c("Negative" = "Patient CMV: negative", "Positive" = "Patient CMV: positive")
)
cell_labs <- as_labeller(
  x = c("CD4_abs_log" = "CD4", "CD8_abs_log" = "CD8")
)
event_labs <- as_labeller(
  x = c(
    "cens" = "Censored", 
    "REL" = "Relapse",
    "NRF_other" = "NRF: Other",
    "NRF_gvhd" = "NRF: GVHD"
  )
)

# Loading objects from targets
tar_load(
  c(
    datasets,
    dli_msdata,
    long_submodels,
    reference_values,
    multivar_allDLI_nointer
  )
)

dat_wide <- datasets$wide
dat_long <- datasets$long

# Prepare datasets for plotting 
dat_wide[, cr_ind := factor(
  x = ifelse(endpoint6_s != "cell_interv", as.character(endpoint6_s), "cens"),
  levels = c("cens", "REL", "NRF_gvhd", "NRF_other")
)]

dat_wide[, endpoint_specify6 := factor(
  x = ifelse(endpoint6 != 24, as.character(endpoint_specify6), "admin-cens")
)]

dat_long[, cr_ind := factor(
  x = ifelse(endpoint6_s != "cell_interv", as.character(endpoint6_s), "cens"),
  levels = c("cens", "REL", "NRF_gvhd", "NRF_other")
)]
```

# Overview

# Descriptives

## Trajectories overall

```{r traj_descript}
melt.data.table(
  data = dat_long,
  id.vars = c("IDAA", "intSCT2_5", "cr_ind"),
  variable.name = "cell_type", 
  value.name = "counts", 
  measure.vars = paste0(c("CD4", "CD8"), "_abs_log")
) %>%
  ggplot(aes(x = intSCT2_5, y = counts)) +
  geom_line(aes(group = IDAA), alpha = 0.75, col = "gray") + 
  geom_smooth(method = "loess", formula = y ~ x, se = FALSE, col = "black") + 
  facet_grid(
    cell_type ~ cr_ind,
    labeller = labeller(cell_type = cell_labs, cr_ind = event_labs)
  ) + 
  scale_y_continuous(
    breaks = log(c(5, 25, 100, 500, 1500)),
    labels = c(5, 25, 100, 500, 1500)
  ) +
  labs(x = "Time since alloHCT (months)", y = "Cell counts") + 
  theme_bw() +
  theme(legend.position = "none")
```

## Measurement schedule

```{r meas_schedule}
dat_long[, max_t := max(intSCT2_5), by = "IDAA"] 

dat_long[, IDAA := reorder(IDAA, max_t)] %>% 
  ggplot(aes(x = intSCT2_5, y = IDAA)) + 
  geom_line(aes(group = IDAA), linetype = "dotted", alpha = 0.5) + 
  geom_point(aes(col = IDAA)) +
  facet_grid(
    cr_ind ~ ., 
    labeller = labeller(cr_ind = event_labs),
    scales = "free_y"
  ) +
  labs(x = "Time since alloHCT (months)", y = "IDAA") + 
  theme_bw() +
  theme(
    legend.position = "none",
    axis.text.y = element_blank()
  ) 
```

# Model

```{r model_summary}
newdat <- expand.grid(
  "ATG" = levels(dat_wide$ATG),
  "VCMVPAT_pre" = levels(dat_wide$VCMVPAT_pre),
  "intSCT2_5" = seq(0.1, 24, by = 0.1)
)

summary_raw <- data.table::data.table(
   round(summary(multivar_allDLI_nointer)$Survival, 3),
   keep.rownames = TRUE
)
data.table::setnames(summary_raw, "rn", "Coefficient")
summary_raw[, event_num := regmatches(
  x = Coefficient,
  m = regexpr(pattern = "[+1-9]$", text = Coefficient)
)]
summary_raw[, event := factor(
   x = event_num,
   levels = seq_len(3),
   labels = c("Relapse", "NRF: Other", "NRF: GVHD")
)]

summary_raw[, Coefficient := gsub(x = Coefficient, pattern = "\\.[+1-9]$", replacement = "")]
summary_raw[, Coefficient := gsub(
  Coefficient, pattern =  "(^.*\\(|_abs_log\\).*$)", replacement = ""
)]

summary_raw[, Coefficient := factor(
  x = Coefficient,
  levels = c("ATG", "hirisk", "DLI", "CD4", "CD8"),
  labels = c("ATG", "Disease risk: high", "DLI", "CD4", "CD8")
)]

data.table::setorder(summary_raw, event, Coefficient)
dt_edit <- summary_raw[, c("event", "Coefficient", "Mean", "2.5%", "97.5%", "P", "Rhat")]
dt_edit[, "Beta [95% CI]" := paste0(
  Mean, " [",
  `2.5%`, ";",
  `97.5%`, "]"
)]

dt_edit[, c("Coefficient", "Beta [95% CI]", "P", "Rhat")] |> 
  kableExtra::kbl(format = "html") |>
  kable_paper("striped", full_width = F) |>
  pack_rows("Relapse", 1, 5) |>
  pack_rows("NRF: GVHD", 6, 9) |>
  pack_rows("NRF: Other", 10, 13)
```


```{r model_trajectories}
# Get model frames
mod <- multivar_allDLI_nointer
terms_FE <- mod$model_info$terms$terms_FE_noResp
model_frames_FE <- lapply(terms_FE, model.frame.default, data = newdat)
modmats_FE <- mapply(
  model.matrix.default,
  object = terms_FE,
  data = model_frames_FE,
  SIMPLIFY = FALSE
)

mcmc_elements <- names(mod$mcmc)
betas_mcmc <- as.list(mod$mcmc[grep("^betas", mcmc_elements, value = TRUE)])
n_samp_posterior <- 2000
betas <- lapply(betas_mcmc, function(b) {
  df_samps <- do.call(rbind.data.frame, b)
  df_samps[sample(nrow(df_samps), size = n_samp_posterior, replace = FALSE), ]
})

preds_ls <- mapply(
  function(modmat, beta) {
    preds_df <- data.table(modmat %*% t(beta))

    res <- preds_df[, ':=' (
      pred = rowMeans(.SD),
      lower = apply(.SD, 1, quantile, probs = 0.025),
      upper = apply(.SD, 1, quantile, probs = 0.975)
    )][, c("pred", "lower", "upper")]

    cbind(newdat, res)
  },
  modmat = modmats_FE,
  beta = betas,
  SIMPLIFY = FALSE
)

df_preds <- rbindlist(preds_ls, idcol = "cell_type")

ggplot(df_preds, aes(intSCT2_5, pred, group = ATG)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "lightgray", alpha = 0.7) +
  geom_line(aes(col = ATG), size = 1.25) +
  facet_grid(
    cell_type ~ VCMVPAT_pre, 
    labeller = labeller(cell_type = cell_labs, VCMVPAT_pre = cmv_labs)
  ) +
  labs(x = "Time since alloHCT (months)", y = "Cell counts") +
  scale_y_continuous(
    breaks = log(c(5, 25, 100, 500, 1500)),
    labels = c(5, 25, 100, 500, 1500)
  ) +
  theme_minimal()
```



