---
title: "Immune reconstitution - descriptives"
author: "Ed Bonneville and Eva Koster"
date: "`r Sys.setenv(LANG = 'en_US.UTF-8'); format(Sys.Date(), '%d %B %Y')`"
output: 
  html_document:
    df_print: kable
    toc: yes
    toc_float: 
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Knitr set-up
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(
  echo = FALSE, 
  out.width = "100%", 
  warning = FALSE, 
  message = FALSE
)
options(knitr.kable.NA = '', scipen = 999)
```


```{r dat_loading}
set.seed(4955628)
library(targets)
tar_load(
  c(
    dat_merged,
    NMA_preDLI_datasets,
    NMA_postDLI_datasets
  )
)

# Theme
theme_set(theme_minimal(base_size = 14))

# Take only NMA cohort
dat_merged_NMA <- dat_merged[TCD2 %in% c("NMA RD: ALT", "UD: ALT + ATG")]

# Make wide data for events
dat_merged_NMA_wide <- data.table::dcast(
    data = dat_merged_NMA,
    formula = IDAA + SCT_May2010 + hirisk + CMV_PD +
      endpoint5_s + endpoint5 + endpoint_specify5 +
      sec_endpoint2 + sec_endpoint2_s + sec_endpoint2_specify +
      HLAmismatch_GvH + relation +
      uDLI + uDLI_s + earlylow_DLI + TCD + TCD2 + TCDmethod ~ .,
    fun = length
  )
data.table::setnames(dat_merged_NMA_wide, old = ".", new = "n_measurements")
```

# Raw (untrimmed) df

To-do:

- Plot of whole follow-up available, labels intermediate events
- Add tabs for the different cell-types
- Possibly use plotly/shiny for checking counts and visualising on log vs original scale 
- Allow to choose certain patients

```{r raw_one}
id_samps <- sample(unique(dat_merged_NMA$IDAA), size = 16, replace = FALSE)

#test_id <- dat_merged_NMA[IDAA %in% id_samps[1]]

# Prepare sequence of events
# - We need DLI, DLI2 (if no events happened before)
samp <- 1

dat_merged_NMA[IDAA %in% id_samps[samp]] |> 
  ggplot(aes(intSCT, CD3_abs)) +
  geom_point(
    size = 3.5, pch = 21,
    alpha = 0.8,
    col = "#359fda",
    fill = colorspace::lighten("#359fda", amount = 0.3)
  ) +
  labs(x = "Months since alloHCT", y = "CD3 counts") +
  
  # Start plotting sequence of events
  geom_vline(
    data = dat_merged_NMA_wide[IDAA %in% id_samps[samp]],
    aes(xintercept = endpoint5), linetype = "dashed"
  )
```

